[tool.poetry]
name = "unichat"
version = "0.1.0"
description = ""
authors = ["Ivan <iivan.zybin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.12"
uvicorn = "^0.34.0"
sqlalchemy = "^2.0.40"
asyncpg = "^0.30.0"
python-socketio = {extras = ["asyncio-client"], version = "^5.12.1"}
redis = "^5.2.1"
alembic = "^1.15.2"
pydantic-settings = "^2.9.1"
fastapi-mail = "^1.4.2"
passlib = "^1.7.4"
pyjwt = "^2.10.1"
python-multipart = "^0.0.20"
dishka = "^1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
