"""empty message

Revision ID: 01f794968799
Revises: 65d2a1fdb2ce
Create Date: 2025-05-04 07:28:43.335099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f794968799'
down_revision: Union[str, None] = '65d2a1fdb2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('student', 'password_hash')
    op.add_column('teacher', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('teacher', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('teacher', 'password')
    op.add_column('student', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('student', 'password')
    # ### end Alembic commands ###
