"""empty message

Revision ID: 03ea53bf6301
Revises: bf61c6954e57
Create Date: 2025-05-03 16:01:38.302742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ea53bf6301'
down_revision: Union[str, None] = 'bf61c6954e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('university', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('university', sa.Column('patronymic', sa.String(length=100), nullable=True))
    op.add_column('university', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('university', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_constraint('university_admin_email_key', 'university', type_='unique')
    op.create_unique_constraint(None, 'university', ['email'])
    op.drop_column('university', 'admin_password_hash')
    op.drop_column('university', 'admin_email')
    op.drop_column('university', 'admin_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('admin_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('university', sa.Column('admin_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('university', sa.Column('admin_password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'university', type_='unique')
    op.create_unique_constraint('university_admin_email_key', 'university', ['admin_email'])
    op.drop_column('university', 'password')
    op.drop_column('university', 'email')
    op.drop_column('university', 'patronymic')
    op.drop_column('university', 'last_name')
    op.drop_column('university', 'first_name')
    # ### end Alembic commands ###
