"""empty message

Revision ID: 092490939dd0
Revises: 01f794968799
Create Date: 2025-05-06 14:00:48.878391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '092490939dd0'
down_revision: Union[str, None] = '01f794968799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_id', table_name='student')
    op.drop_constraint('student_email_key', 'student', type_='unique')
    op.create_foreign_key(None, 'student', 'user', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('student', 'updated_at')
    op.drop_column('student', 'first_name')
    op.drop_column('student', 'created_at')
    op.drop_column('student', 'patronymic')
    op.drop_column('student', 'password')
    op.drop_column('student', 'email')
    op.drop_column('student', 'last_name')
    op.drop_index('ix_teacher_id', table_name='teacher')
    op.drop_constraint('teacher_email_key', 'teacher', type_='unique')
    op.create_foreign_key(None, 'teacher', 'user', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('teacher', 'updated_at')
    op.drop_column('teacher', 'first_name')
    op.drop_column('teacher', 'created_at')
    op.drop_column('teacher', 'patronymic')
    op.drop_column('teacher', 'password')
    op.drop_column('teacher', 'email')
    op.drop_column('teacher', 'last_name')
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.add_column('teacher', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('teacher', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('teacher', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('teacher', sa.Column('patronymic', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('teacher', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('teacher', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_unique_constraint('teacher_email_key', 'teacher', ['email'])
    op.create_index('ix_teacher_id', 'teacher', ['id'], unique=True)
    op.add_column('student', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('patronymic', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_unique_constraint('student_email_key', 'student', ['email'])
    op.create_index('ix_student_id', 'student', ['id'], unique=True)
    # ### end Alembic commands ###
