"""empty message

Revision ID: 65d2a1fdb2ce
Revises: 03ea53bf6301
Create Date: 2025-05-03 16:36:31.380622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d2a1fdb2ce'
down_revision: Union[str, None] = '03ea53bf6301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_department_in_institute', 'department', type_='unique')
    op.drop_constraint('uq_group_in_department', 'group', type_='unique')
    op.drop_constraint('uq_institute_in_university', 'institute', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_institute_in_university', 'institute', ['university_id', 'name'])
    op.create_unique_constraint('uq_group_in_department', 'group', ['department_id', 'name'])
    op.create_unique_constraint('uq_department_in_institute', 'department', ['institute_id', 'name'])
    # ### end Alembic commands ###
