"""empty message

Revision ID: eed6df5b4516
Revises: 512b5e9b600a
Create Date: 2025-04-27 16:11:16.580515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed6df5b4516'
down_revision: Union[str, None] = '512b5e9b600a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=200), nullable=False))
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
